AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-minsait-prova-aws-fullstack
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Resources:
  AmplifyAppLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      Timeout: 60
      CodeUri: ./src
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - amplify:CreateApp
                - amplify:CreateBranch
                - amplify:StartDeployment
              Resource: '*'
  # helloFromLambdaFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
  #     Runtime: nodejs20.x
  #     Architectures:
  #     - x86_64
  #     MemorySize: 128
  #     Timeout: 100
  #     Description: A Lambda function that returns a static string.
  #     Policies:
  #     - AWSLambdaBasicExecutionRole

